import type { Metadata } from "next";
import AuthGuard from "./components/auth/auth-guard";
import { AuthProvider } from "./lib/context/auth-context";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
          <AuthProvider>
              {children}
        </AuthProvider>
      </body>
    </html>
  );
}
